version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:24"
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - adaptive
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "07:24"
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - adaptive